server:
  port: 0
spring:
  application:
    name: user-service
  datasource:
      url: jdbc:h2:mem:testDB
      username: sa
      password: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  boot:
    admin:
      client:
        url:
        - http://localhost:8888
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'